# Generated by Django 4.1.5 on 2023-03-27 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("user_email", models.EmailField(max_length=254)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="/profiles/profile_pic_green.png",
                        null=True,
                        upload_to="profiles/",
                        verbose_name="Profile Picture",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="generatedWebsites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webId", models.TextField()),
                ("templateId", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to="app.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="businessTemplateDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("templateId", models.TextField()),
                ("name", models.TextField(max_length=255)),
                ("description", models.TextField(max_length=255)),
                ("type", models.TextField(max_length=255)),
                ("missionStatement", models.TextField(max_length=1500)),
                (
                    "template_choice",
                    models.CharField(
                        choices=[
                            ("medical_office", "Medical Office"),
                            ("Blog", "Blog"),
                            ("Phillip", "Phillip"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business",
                        to="app.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="businessContactInfoDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(max_length=255)),
                ("phoneNumber", models.IntegerField(verbose_name="phone number")),
                ("address", models.TextField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="app.businesstemplatedatabase",
                    ),
                ),
            ],
        ),
    ]
