# Generated by Django 4.1.5 on 2023-03-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesstemplatedatabase",
            name="template_choice",
            field=models.CharField(
                choices=[
                    ("medical_office", "Medical Office"),
                    ("Blog", "Blog"),
                    ("Restaurant", "Restaurant"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
